spring:
  application:
    name: transfer-service

  datasource:
    url: jdbc:postgresql://localhost:5432/transfer_bank
    username: postgres
    password: postgres

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: transfer-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.tbs.transfer.service.transfer
        spring.json.use.type.headers: true
        spring.json.type.mapping: >
          debit-completed:com.tbs.transfer.service.transfer.DebitCompleted,
          fraud-analysis-result:com.tbs.transfer.service.transfer.FraudAnalysisResult

server:
  port: 8080